name: Rust

on:
  push:
    branches: [ "web" ]
  pull_request:
    branches: [ "web" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: nightly
        targets: wasm32-unknown-unknown
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo build --release --target wasm32-unknown-unknown
