name: Rust

on:
  push:
    branches: [ "web" ]
  pull_request:
    branches: [ "web" ]
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: nightly
        targets: wasm32-unknown-unknown
    
    - uses: actions/checkout@master
    
    - uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true

    - name: Build WASM
      run: cargo build --release --target wasm32-unknown-unknown

    - name: Install Bindgen
      run:  cargo install wasm-bindgen-cli     
   
    - name: Copy assets
      run: cp -r assets web/assets 

    - name: Generate WASM bindings
      run: wasm-bindgen --out-name bevy-ascii-game --out-dir web --target web target/wasm32-unknown-unknown/release/bevy-ascii-game.wasm

    - name: Deploy to pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web
        branch: github-pages
